version: "0.2"
words:
  - adguard
  - adlist
  - airsonic
  - akadmin
  - aliasgroup
  - allowtransparency
  - apitoken
  - appname
  - appnamehere
  - auditlog
  - authentik
  - authexample
  - authkey
  - authtoken
  - autoconnect
  - autoplay
  - autoscan
  - autosync
  - backupname
  - basicauthexample
  - batnoter
  - bazarr
  - Blocklists
  - blocktype
  - bugfixer's
  - bungeecord
  - cacher
  - chainname
  - cheatsheet
  - chronos
  - cifs
  - clouddns
  - cloudflared
  - cloudflareddns
  - collabora
  - configfile
  - configfiles
  - configmap
  - containo
  - cooldown
  - crossplay
  - csgo
  - cuda
  - daemonset
  - DASHDOT
  - DATAPOINTS
  - datascience
  - dbcreds
  - dbengine
  - ddns
  - djava
  - dnat
  - dnsserver
  - dnsservers
  - dockerized
  - duplicati
  - dynmap
  - ebgp
  - elif
  - emby
  - entrypoints
  - eptgmk
  - EXIF
  - fireshare
  - flatnotes
  - flemarr
  - Flemmarr
  - flushtables
  - forcegc
  - fullname
  - geoip
  - geoipupdate
  - gibibyte
  - gluster
  - goauthentik
  - Groupname
  - gunicorn
  - healthcheck
  - healthchecks
  - healthz
  - hexo
  - honeybadger
  - hostnames
  - hostpath
  - hyperconverged
  - hyperthread
  - iban
  - idtool
  - immich
  - ingressclasses
  - ingressroutes
  - ingressroutetcps
  - ingressrouteudps
  - integrationsenabled
  - inventree
  - ipaddr
  - ixcert
  - ixsystems
  - jackett
  - jacobalberty
  - jailman
  - javaprefs
  - jovyan
  - kavita
  - keepalive
  - killswitch
  - Kiwix
  - kjeld
  - kube
  - kubeconfig
  - kubectl
  - kubernetes
  - lancache
  - ldapldap
  - ldapldaps
  - ldapmetrics
  - ldaps
  - lebbing
  - lenpaste
  - letsencrypt
  - lidarr
  - linkwallet
  - loadbalancer
  - localcnamerecords
  - localdnsrecords
  - localdomain
  - localpref
  - logfile
  - loolwsd
  - mailenabled
  - mailgun
  - mapbox
  - mariadbcreds
  - mattwebbio
  - maxmind
  - mbit
  - mediafiles
  - memfs
  - mergerfs
  - meshroom
  - metallb
  - microbin
  - Midarr
  - middlewares
  - middlewaretcps
  - mikrotik
  - milicpu
  - mimetypes
  - minecraft
  - minio
  - modelstore
  - modports
  - mongosh
  - mountpoint
  - multihost
  - nbclassic
  - neko
  - netdata
  - networkv
  - nextcloud
  - nobind
  - nocaptcha
  - nodeport
  - nodeports
  - nohardlinks
  - noisedash
  - notebookbar
  - OOKLA
  - ornias
  - ovpn
  - passwrd
  - pgid
  - photoprism
  - pihole
  - plainhost
  - plaxt
  - playout
  - plex
  - plextraktsync
  - portainer
  - preconfigured
  - prefs
  - preload
  - proto
  - proxyhttp
  - proxyhttps
  - proxymetrics
  - puid
  - putregexhere
  - pvcname
  - pvcpath
  - Pyspark
  - qbitmanage
  - quotum
  - radarr
  - raknet
  - ramdisk
  - rclone
  - rcon
  - rcontcp
  - recaptha
  - recordtypes
  - recyclarr
  - rediscreds
  - regexlist
  - registeringats
  - reneg
  - replacementurlhere
  - resolv
  - restreamer
  - rtmp
  - rtmps
  - sabnzbd
  - schouten
  - Scipy
  - selfsigned
  - sendgrid
  - serverconfig
  - servername
  - serverstransports
  - serviceexpert
  - sgateway
  - signup
  - smallblock
  - somefile
  - somethingelse
  - sonarr
  - sonarrsabnzbd
  - sonatype
  - speedtest
  - speedtests
  - srcsets
  - ssvnc
  - statefulset
  - staticdhcpleases
  - staticfiles
  - steamcommunica
  - steammasterser
  - subchart
  - sublist
  - subquestion
  - subquestions
  - svcname
  - syncthing
  - tailscale
  - targetport
  - tccr
  - teamspeak
  - testpassword
  - testuser
  - themenamehere
  - tlsoptions
  - tlsstores
  - traefik
  - traefikservices
  - trakt
  - truecharts
  - truenas
  - truetool
  - umami
  - unet
  - unifi
  - Upstreams
  - userspace
  - vaapi
  - valheim
  - vaultwarden
  - vdev
  - vm's
  - watchyourlan
  - webbasecontrol
  - webpanel
  - websecure
  - websockets
  - webworkers
  - weejewel
  - wger
  - whisparr
  - xsystems
  - zerotier
  - zwavejs
